# Generated by Django 5.2.1 on 2025-12-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_followus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUs',
        ),
    ]
